### ISSUE TITLE
GOTIFY_APP_TOKEN not defined in ENV

### ISSUE THREAD

**Issue by D3rJust1n** [FoxxMD/deploy-gotify-alerter#2]
Every time I want to start the stack I get this message and the stack stops.
Do you have any idea how I can solve this? the token is freshly created and also works when I push a test message with the gotify-cli

![Image](https://github.com/user-attachments/assets/617277ff-2f4e-4867-950b-0d74e9f6f280)

compose.yml
```yml
services:
  komodo-gotify:
    image: foxxmd/komodo-gotify-alerter:latest
    container_name: gotify-alerter
    environment:
      - GOTIFY_URL=${GOTIFY_URL}
      - GOTIFY_APP_TOKEN=${GOTIFY_API_KEY}
      - UNRESOLVED_TIMEOUT_TYPES=ServerCpu,ServerMem
      - UNRESOLVED_TIMEOUT=20000

    ports:
      - "7000:7000"
```

.env
```yml
GOTIFY_URL=https://gotify.d3rjust1n.xyz
GOTIFY_APP_TOKEN=A_GDBc8QtT4s2XY
```
