### ISSUE TITLE
Error on Test Alerter

### ISSUE THREAD

**Issue by D3rJust1n** [FoxxMD/deploy-gotify-alerter#4]
I get the following error wenn clicking on test alerter
The gotify url and the token are valid

The IP in the endpoint is the IP from my host machine

```
ERROR: Failed to send alert to Custom Alerter gotify

TRACE:
	1: failed at post request to alerter
	2: Error with request: reqwest::Error { kind: Request, url: "http://192.168.178.231:7000/", source: hyper_util::client::legacy::Error(Connect, ConnectError("tcp connect error", Os { code: 110, kind: TimedOut, message: "Connection timed out" })) }
```

![Image](https://github.com/user-attachments/assets/312036db-c49b-4294-8f61-bced14ee4128)

**Comment by FoxxMD** [comment]
Can you please paste the Toml (upper right hand corner) for the **Stack** you created for deploy-gotify-alerter? Is it on the same host machine?

**Comment by D3rJust1n** [comment]
gotify is located on a different machine than the gotify alerter and komodo
here is the toml

```toml
[[alerter]]
name = "gotify"
[alerter.config]
enabled = true
endpoint.type = "Custom"
endpoint.params.url = "http://192.168.178.231:7000"
alert_types = [
  "StackImageUpdateAvailable",
  "StackAutoUpdated"
]
```

**Comment by FoxxMD** [comment]
Please post the Toml for the deploy-gotify-alerter **Stack**.

**Comment by D3rJust1n** [comment]
```toml
[[stack]]
name = "gotify-alerter"
[stack.config]
server = "p310"
files_on_host = true
run_directory = "/home/just1n/Homelab/gotify-alerter"
file_paths = ["compose.yml"]
```

**Comment by FoxxMD** [comment]
Is the contents of `compose.yml` exactly the same as what is [found in this repo?](https://github.com/FoxxMD/deploy-gotify-alerter/blob/main/compose.yaml) Is the stack running?

If it's not exactly the same please post the compose.yml contents.

**Comment by D3rJust1n** [comment]
it is the content of the stack in the readme under “manual setup”

```yml
services:
  komodo-gotify:
    image: foxxmd/komodo-gotify-alerter:latest
    container_name: gotify-alerter
    restart: always
    environment:
      - GOTIFY_URL=${GOTIFY_URL}
      - GOTIFY_APP_TOKEN=${GOTIFY_APP_TOKEN}
      - UNRESOLVED_TIMEOUT_TYPES=ServerCpu,ServerMem
      - UNRESOLVED_TIMEOUT=20000

    ports:
      - "7000:7000"
```
